import sys
import re

def process_file(filepath):
    print("Processing", filepath)
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()

    if 'profile/page.js' in filepath:
        content = content.replace('bg-zinc-950', 'bg-white')
        content = content.replace('bg-zinc-900/80', 'bg-white border-b border-neutral-200')
        content = content.replace('bg-zinc-900', 'bg-white border text-black border-neutral-200')
        content = content.replace('bg-zinc-800', 'bg-neutral-100')
        content = content.replace('bg-zinc-950', 'bg-white')
        content = content.replace('text-zinc-100', 'text-neutral-900')
        content = content.replace('text-white', 'text-black')
        content = content.replace('text-zinc-400', 'text-neutral-500')
        content = content.replace('text-zinc-500', 'text-neutral-500')
        content = content.replace('text-zinc-600', 'text-neutral-400')
        content = content.replace('text-zinc-700', 'text-neutral-400')
        content = content.replace('border-zinc-800', 'border-neutral-200')
        content = content.replace('border-zinc-700', 'border-neutral-300')
        content = content.replace('text-teal-400', 'text-black')
        content = content.replace('text-teal-500', 'text-black')
        content = content.replace('bg-teal-500/10', 'bg-neutral-100')
        content = content.replace('bg-gradient-to-br from-teal-900/60 via-zinc-900 to-zinc-900', 'bg-neutral-50 border-b border-neutral-200')
        content = content.replace('bg-gradient-to-br from-teal-500 to-teal-700', 'bg-black text-white')
        content = content.replace('text-red-400', 'text-black font-bold')
        content = content.replace('bg-red-500/5', 'bg-neutral-50')
        content = content.replace('bg-red-500/10', 'bg-neutral-100')
        content = content.replace('border-red-900/30', 'border-neutral-300')
        content = re.sub(r'bg-[a-z]+-500/10', 'bg-neutral-100', content)
        
    if 'trips/page.js' in filepath:
        content = content.replace('bg-zinc-950', 'bg-white')
        content = content.replace('bg-zinc-900/80', 'bg-white border-b border-neutral-200')
        content = content.replace('bg-zinc-900', 'bg-white border text-black border-neutral-200')
        content = content.replace('bg-zinc-800', 'bg-neutral-100')
        content = content.replace('bg-zinc-950', 'bg-white')
        content = content.replace('text-zinc-100', 'text-neutral-900')
        content = content.replace('text-white', 'text-black')
        content = content.replace('text-zinc-400', 'text-neutral-500')
        content = content.replace('text-zinc-500', 'text-neutral-500')
        content = content.replace('text-zinc-600', 'text-neutral-400')
        content = content.replace('text-zinc-700', 'text-neutral-400')
        content = content.replace('border-zinc-800', 'border-neutral-200')
        content = content.replace('border-zinc-700', 'border-neutral-300')
        content = content.replace('text-teal-400', 'text-black')
        content = content.replace('text-teal-500', 'text-black')
        content = content.replace('bg-teal-500/10', 'bg-neutral-100')
        content = content.replace('bg-teal-600', 'bg-black text-white')
        content = content.replace('bg-teal-500', 'bg-black')
        content = content.replace('border-teal-500', 'border-black')
        content = re.sub(r'bg-[a-z]+-500/10', 'bg-neutral-100', content)
        content = re.sub(r'border-[a-z]+-500/30', 'border-neutral-200', content)
        content = re.sub(r'text-[a-z]+-400', 'text-black', content)

    if 'reports/page.js' in filepath:
        content = content.replace('bg-zinc-950', 'bg-white')
        content = content.replace('bg-zinc-900/80', 'bg-white border-b border-neutral-200')
        content = content.replace('bg-zinc-900', 'bg-white border text-black border-neutral-200')
        content = content.replace('bg-zinc-800', 'bg-neutral-100')
        content = content.replace('bg-zinc-950', 'bg-white')
        content = content.replace('text-zinc-100', 'text-neutral-900')
        content = content.replace('text-white', 'text-black')
        content = content.replace('text-zinc-400', 'text-neutral-500')
        content = content.replace('text-zinc-500', 'text-neutral-500')
        content = content.replace('text-zinc-600', 'text-neutral-400')
        content = content.replace('text-zinc-700', 'text-neutral-400')
        content = content.replace('border-zinc-800', 'border-neutral-200')
        content = content.replace('border-zinc-700', 'border-neutral-300')
        content = content.replace('text-teal-400', 'text-black')
        content = content.replace('text-teal-500', 'text-black')
        content = content.replace('bg-teal-600', 'bg-black text-white text-bold bg-opacity-100')
        content = content.replace('bg-teal-600/10', 'bg-black text-white text-bold')
        content = content.replace('bg-teal-500', 'bg-black')
        content = content.replace('border-teal-500', 'border-black')
        content = content.replace('bg-gradient-to-br from-teal-600 to-teal-700', 'bg-white text-black border-neutral-200 border-2')
        content = content.replace('text-teal-100', 'text-black font-bold')
        content = content.replace('text-teal-200', 'text-black font-bold')
        content = content.replace('text-[#f97316]', 'text-black')
        # fix color maps
        content = re.sub(r'color:\s*\"#[a-f0-9]+\"', 'color: "#171717"', content)
        content = content.replace('fill={entry.color}', 'fill={entry.color}') 
        content = content.replace('fill={e.color}', 'fill={e.color}')
        
        # fix gradient inside reports
        content = content.replace('bg-gradient-to-br from-zinc-900 to-zinc-800', 'bg-neutral-50')
        content = content.replace('bg-zinc-900/50', 'bg-white')

    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(content)

process_file('d:/my-trip-expense/app/profile/page.js')
process_file('d:/my-trip-expense/app/trips/page.js')
process_file('d:/my-trip-expense/app/reports/page.js')
